# Generated by Django 2.1.7 on 2019-04-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StyleTransferModel',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('content_image', models.ImageField(blank=True, upload_to='')),
                ('content_weight', models.IntegerField(blank=True)),
                ('style_image', models.ImageField(blank=True, upload_to='')),
                ('style_weight', models.IntegerField(blank=True)),
                ('transfer_epoch', models.IntegerField(blank=True)),
                ('transfer_image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
