# Generated by Django 2.1.7 on 2019-04-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styletransfermodel',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='styletransfermodel',
            name='content_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='styletransfermodel',
            name='style_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='styletransfermodel',
            name='style_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='styletransfermodel',
            name='transfer_epoch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='styletransfermodel',
            name='transfer_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
