# Generated by Django 2.1.7 on 2019-04-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0002_auto_20190407_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='styletransfermodel',
            name='id_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
