# Generated by Django 2.1.7 on 2019-04-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0003_styletransfermodel_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styletransfermodel',
            name='id_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
