# Generated by Django 2.1.7 on 2019-04-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0004_auto_20190407_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styletransfermodel',
            name='content_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='styletransfermodel',
            name='style_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
