# Generated by Django 2.1.7 on 2019-04-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0005_auto_20190407_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='styletransfermodel',
            name='learning_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='styletransfermodel',
            name='variation_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
